name: Publish Python Package

on:
  push:
    branches:
      - main  # Runs on every commit to main branch

jobs:
  publish:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: |
          pip install poetry
        
      - name: Update version
        run: |
          python .github/workflows/update_version.py

      - name: Configure Poetry
        env: 
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
          POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/

      - name: Build package
        run: poetry build

      - name: Publish to TestPyPI
        run: |
          poetry publish -r testpypi
          echo "hi2"

      - name: Publish to PyPI
        if: steps.publish.conclusion == 'success'
        run: poetry publish
